In [53]:
# open cv patterns
# zach fredin, 2021

# generates Oxford-friendly Gcode for a checkerboard pattern

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def oxford_intro(power, feed, file):
    f = open(file, 'x') # open file, checking for existing
    f.write(';--- wow checkerboards ---\n\n')
    f.write('DVAR $POWER\n')
    f.write('DVAR $FEED\n')
    f.write('$POWER=%s\n' % power)
    f.write('$FEED=%s\n' % feed)
    f.write('G90\n')
    f.write('G71\n')
    f.write('G92 X0 Y0 Z0\n')
    f.write('G108\n')
    f.write('FARCALL "ATTENUATOR.PGM" s$POWER\n')
    f.write('MSGCLEAR -1\n')
    f.write('MSGDISPLAY 1, "program started"\n\n')
    f.close

def write_square(x, y, size, hatch, file):
    passes = int(size / hatch)
    f = open(file, 'a') # open file for appending
    f.write('BEAMOFF\n')
    f.write('G01 X%.4f Y%.4f F$FEED\n' % (x, y))
    f.write('BEAMON\n')
    for i in range(1, passes): # x hatches
        f.write('G01 Y%.4f F$FEED\n' % (i * hatch + y))
        f.write('G01 X%.4f F$FEED\n' % (size + x))
        f.write('G01 X%.4f F$FEED\n' % x)
    f.write('BEAMOFF\n')
    f.close

def make_checkerboard(x_qty, y_qty, sq_size, hatch, file, power, feed):
    oxford_intro(power, feed, file)
    for i in range(1, x_qty + 1):
        for j in range(1, y_qty + 1):
            if (i + j) % 2 == 0:
                write_square(float(i) * sq_size, float(j) * sq_size, sq_size, hatch, file)
                
make_checkerboard(12, 9, 1.5, 0.01, 'checkerboard.pgm', 2, 3)

In [7]:
# aruco marker generation test

import numpy as np
import cv2

aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_6X6_100)
img = cv2.aruco.drawMarker(aruco_dict, 1, 8)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

print(img)

[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 255 255   0]
 [  0 255   0 255 255 255 255   0]
 [  0 255   0 255 255 255   0   0]
 [  0 255   0   0   0 255 255   0]
 [  0 255   0   0   0 255   0   0]
 [  0   0 255   0   0   0 255   0]
 [  0   0   0   0   0   0   0   0]]


In [29]:
# aruco pattern via oxford
# zach fredin, 2021

# generates Oxford-friendly Gcode for a single aruco marker

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import cv2

def oxford_intro(power, feed, file):
    f = open(file, 'x') # open file, checking for existing
    f.write(';--- wow checkerboards ---\n\n')
    f.write('DVAR $POWER\n')
    f.write('DVAR $FEED\n')
    f.write('$POWER=%s\n' % power)
    f.write('$FEED=%s\n' % feed)
    f.write('G90\n')
    f.write('G71\n')
    f.write('G92 X0 Y0 Z0\n')
    f.write('G108\n')
    f.write('FARCALL "ATTENUATOR.PGM" s$POWER\n')
    f.write('MSGCLEAR -1\n')
    f.write('MSGDISPLAY 1, "program started"\n\n')
    f.close

def write_square(x, y, size, hatch, file):
    passes = int(size / hatch)
    f = open(file, 'a') # open file for appending
    f.write('BEAMOFF\n')
    f.write('G01 X%.4f Y%.4f F$FEED\n' % (x, y))
    f.write('BEAMON\n')
    for i in range(1, passes): # x hatches
        f.write('G01 Y%.4f F$FEED\n' % (i * hatch + y))
        f.write('G01 X%.4f F$FEED\n' % (size + x))
        f.write('G01 X%.4f F$FEED\n' % x)
    f.write('BEAMOFF\n')
    f.close
    
def make_aruco(sq_size, hatch, file, power, feed):
    oxford_intro(power, feed, file)
    aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_6X6_100)
    img = cv2.aruco.drawMarker(aruco_dict, 1, 8)
    for i in range(0, 8):
        for j in range(0, 8):
            if img[i][j] == 0:
                write_square(float(i) * sq_size, float(j) * sq_size, sq_size, hatch, file)

make_aruco(2, 0.01, 'aruco.pgm', 2, 3) 
